#include<stdio.h>
#include<conio.h>
void main()
{
  clrscr();
  int num,i,flag=0;

  printf("Enter a number: ");
  scanf("%d",&num);

  if (num <= 1)
  {
    printf("%d is NOT a Prime Number ",num);
    getch();
    return;
  }

    for (i = 2; i <= num / 2; i++)
    {
      if (num % i == 0)
      {
	flag = 1;
	break;
      }
    }
     if (flag == 0)
       printf("%d is a Prime Number\n",num);
     else
       printf("%d is NOT a Prime Number\n",num);
   getch();
}